# Generated by Django 3.0.1 on 2019-12-20 10:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('cnpj', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('endereco', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('compra', models.BooleanField(default=False, null=True)),
                ('venda', models.BooleanField(default=False, null=True)),
                ('doacao', models.BooleanField(default=False, null=True)),
                ('coleta', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa_Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('qualidade', models.CharField(max_length=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=80)),
                ('empresas', models.ManyToManyField(related_name='materiais', through='app.Empresa_Material', to='app.Empresa')),
            ],
        ),
        migrations.AddField(
            model_name='empresa_material',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Material'),
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificacao', models.CharField(max_length=80)),
                ('empresas', models.ManyToManyField(related_name='certificados', to='app.Empresa')),
            ],
        ),
    ]
