# Generated by Django 3.0.1 on 2019-12-20 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='empresas',
        ),
        migrations.AlterField(
            model_name='empresa_material',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='app.Empresa'),
        ),
        migrations.AlterField(
            model_name='empresa_material',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='app.Material'),
        ),
    ]
