# Generated by Django 3.0.1 on 2019-12-20 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191220_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='empresas',
            field=models.ManyToManyField(related_name='materiais', through='app.Empresa_Material', to='app.Empresa'),
        ),
        migrations.AlterField(
            model_name='empresa_material',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Empresa'),
        ),
        migrations.AlterField(
            model_name='empresa_material',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Material'),
        ),
    ]
